### ISSUE TITLE
Interpret variables in formulas?

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [abagames/folmura#2]
There are two free variables I don't know how to interpret. I'm guessing "t" is "time". "i" is a total mystery to me.

And there are some bound variables that I don't know how to interpret. I'm guessing "x" and "y" are horizontal and vertical position (or maybe vice versa). "w", "h", "H", "S" and "B" are total mysteries to me.

I'm guessing "a" and "b" are meaningless except to the extent that they are used in other functions, but for all I know I'm wrong about that too.

**Comment by abagames** [comment]
t = time (second)
i = index of the point (The canvas consists of n (10 to 100) points connected with lines and each have an index starting from 0)
x/y = horizontal/vertical position of each point
w/h = width/height of each point ((width + height) / 2 is used as a stroke weight of each line)
H/S/B = color(Hue/Saturation/Brightness) of each point
a/b = random integer value (2 to 10)

**Comment by JeffreyBenjaminBrown** [comment]
Cool, those are nice and meaningful. I wonder whether the readme might be a natural place to list them? (My curiosity is satisfied, but other visitors might not be savvy enough to discover this issue in the issue tracker.)
